name: 'Secrets_To_Env'
description: 'Repository Secrets_To_Env'
branding:
  icon: 'crop'
  color: 'orange'
inputs:
  secrets_json:
    description: 'secrets_json'
    required: true
    default: '{"默认": "default"}'

  file_name:
    description: '要存放环境变量的文件名'
    required: false
    default: '.env'

runs:
  using: "composite"
  steps:
    - name: start run
      shell: bash
      run: |
        filename="Secrets_To_Env.json"
        data='${{ inputs.secrets_json }}'
        echo "$data" > $filename
     
        jq -r 'to_entries[] | "\(.key)=\"\(.value)\""' $filename > ${{ inputs.file_name }}
        cat ${{ inputs.file_name }} | sed 's/^/export /' >> ~/.bashrc
        source ~/.bashrc
        rm -r $filename
        echo "当前用户：$(whoami)"
        echo "环境变量文件：$(ls ~/.bashrc)"

