name: Test

on:
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Secrets_To_Env
          uses: zhlhlf/Secrets_To_Env@master
          with:
            secrets_json: ${{ toJSON(secrets) }}

        - name: test-env
          run: |
            tail -n 15 ~/.bashrc
            source ~/.bashrc
            echo $RCK
