name: Test

on:
  workflow_dispatch:

    inputs:
      ssh:
        description: 'ssh'
        required: true
        default: 'false'
        type: boolean   
        
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Secrets_To_Env
          uses: zhlhlf/Secrets_To_Env@master
          with:
            secrets_json: ${{ toJSON(secrets) }}

        - name: test-env
          run: |
            tail -n 15 ~/.bashrc
            . ~/.bashrc
            echo $RCK

        - name: 高级操作
          if: github.event.inputs.ssh == 'true'
          run: |
            curl -SL http://raw.github.com/zhlhlf/text/main/ssh.sh | sudo bash    
    
