name: Test

on:
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-20.04

      steps:
        - name: 更改交换空间并link构建空间
          uses: zhlhlf/Secrets_To_Env@master
          with:
            secrets_json: '{"asd":"12345"}'